NEWS_STATUSES = {
    "detected",
    "registered",
    "classified",
    "validating",
    "verified",
    "partially_verified",
    "rumor",
    "monitoring",
    "rejected",
    "prioritized",
    "drafting",
    "reviewing",
    "approved",
    "scheduled",
    "published",
    "distributed",
    "measured",
    "archived",
    "corrected",
    "retracted",
    "escalated",
}

AGENT_EXECUTION_STATUSES = {
    "queued",
    "running",
    "waiting_context",
    "waiting_tool",
    "waiting_approval",
    "completed",
    "completed_with_warnings",
    "failed",
    "blocked_by_policy",
    "rejected",
    "cancelled",
    "retrying",
    "escalated",
}

SOURCE_STATUSES = {
    "proposed",
    "active",
    "trusted",
    "watchlist",
    "restricted",
    "blocked",
    "archived",
}

TRUST_LEVELS = {"T0", "T1", "T2", "T3"}

AUDIT_STATUSES = {"pass", "fail", "warning", "pending", "passed", "passed_with_warnings", "failed"}
AUDIT_SEVERITIES = {"low", "medium", "high", "critical"}
NEWS_PRIORITIES = {"P0", "P1", "P2", "P3", "P4"}

VERIFICATION_STATUSES = {
    "unverified",
    "validating",
    "verified",
    "partially_verified",
    "rumor",
    "contradicted",
    "rejected",
    "escalated",
    "monitoring",
    "outdated",
}
EVIDENCE_LEVELS = {"E0", "E1", "E2", "E3", "E4", "E5", "unknown"}
CONFIDENCE_LEVELS = {"C0", "C1", "C2", "C3", "C4", "C5", "unknown"}

RISK_LEVELS = {"low", "medium", "high", "critical", "unknown"}
RISK_SEVERITIES = {"R-SEV-0", "R-SEV-1", "R-SEV-2", "R-SEV-3", "R-SEV-4"}
RISK_DECISION_RECOMMENDATIONS = {
    "allow",
    "allow_with_minor_edits",
    "revise_before_publication",
    "require_human_review",
    "escalate",
    "block_publication",
    "hold_for_verification",
    "reject",
    "monitor_only",
}

CONTENT_TYPES = {
    "editorial_brief",
    "news_article",
    "analysis",
    "explainer",
    "newsletter_item",
    "linkedin_post",
    "blog_article",
    "script_base",
    "internal_note",
}
CONTENT_STATUSES = {"drafting", "reviewing", "approved", "rejected", "blocked", "archived"}

DISTRIBUTION_CHANNELS = {
    "YouTube",
    "YouTube Shorts",
    "TikTok",
    "Instagram Reels",
    "X / Twitter",
    "LinkedIn",
    "Newsletter",
    "Blog / Web",
    "Telegram",
    "Discord",
    "internal",
}
DISTRIBUTION_TYPES = {
    "primary_publication",
    "secondary_distribution",
    "clip_distribution",
    "thread_distribution",
    "newsletter_distribution",
    "community_distribution",
    "blog_distribution",
    "video_distribution",
    "alert_distribution",
    "scheduled_distribution",
    "follow_up_distribution",
    "internal_monitoring",
}
DISTRIBUTION_STATUSES = {
    "proposed",
    "ready_for_review",
    "needs_approval",
    "needs_source",
    "needs_verification",
    "needs_risk_review",
    "needs_channel_variant",
    "needs_schedule",
    "blocked",
    "rejected",
    "scheduled",
    "distributed",
    "archived",
}

PUBLICATION_STATUSES = {
    "scheduled",
    "published",
    "failed",
    "cancelled",
    "corrected",
    "retracted",
    "archived",
}

WORKFLOW_TYPES = {
    "editorial_pipeline",
    "breaking_news_pipeline",
    "video_pipeline",
    "social_pipeline",
    "publication_pipeline",
}
WORKFLOW_RUN_STATUSES = {
    "created",
    "running",
    "waiting_input",
    "waiting_review",
    "blocked",
    "completed",
    "cancelled",
    "failed",
    "escalated",
}
WORKFLOW_STEPS = {
    "intake",
    "source_review",
    "verification",
    "risk_review",
    "content_creation",
    "audit_review",
    "distribution_planning",
    "publication",
    "measurement",
    "memory_review",
    "knowledge_update",
    "completed",
}
WORKFLOW_READINESS_STATUSES = {
    "not_ready",
    "partially_ready",
    "ready_for_review",
    "ready_to_advance",
    "blocked",
    "completed",
}
WORKFLOW_NEXT_AGENTS = {
    "NewsScoutAgent",
    "SourceValidatorAgent",
    "RiskAgent",
    "MarketImpactAgent",
    "EditorialAgent",
    "ScriptAgent",
    "SocialClipAgent",
    "DistributionAgent",
    "AuditAgent",
    "CalendarAgent",
    "MetricsAgent",
    "MemoryAgent",
    "KnowledgeAgent",
    "None",
}
WORKFLOW_STEP_STATUSES = {
    "pending",
    "ready",
    "running",
    "waiting_dependency",
    "completed",
    "skipped",
    "blocked",
    "failed",
}

AGENT_NAMES = {
    "NewsScoutAgent",
    "SourceValidatorAgent",
    "RiskAgent",
    "MarketImpactAgent",
    "EditorialAgent",
    "ScriptAgent",
    "SocialClipAgent",
    "DistributionAgent",
    "AuditAgent",
    "MemoryAgent",
    "KnowledgeAgent",
    "CalendarAgent",
    "MetricsAgent",
}
AGENT_OUTPUT_TYPES = {
    "news_scout_report",
    "source_review",
    "risk_review",
    "market_impact_assessment",
    "editorial_output",
    "script_output",
    "social_output",
    "distribution_plan_output",
    "audit_check_output",
    "memory_proposal",
    "knowledge_graph_proposal",
    "calendar_recommendation",
    "metrics_review",
    "workflow_recommendation",
    "generic_agent_output",
}
AGENT_OUTPUT_TYPES_BY_AGENT = {
    "NewsScoutAgent": {"news_scout_report", "generic_agent_output", "workflow_recommendation"},
    "SourceValidatorAgent": {"source_review", "generic_agent_output", "workflow_recommendation"},
    "RiskAgent": {"risk_review", "generic_agent_output", "workflow_recommendation"},
    "MarketImpactAgent": {
        "market_impact_assessment",
        "generic_agent_output",
        "workflow_recommendation",
    },
    "EditorialAgent": {"editorial_output", "generic_agent_output", "workflow_recommendation"},
    "ScriptAgent": {"script_output", "generic_agent_output", "workflow_recommendation"},
    "SocialClipAgent": {"social_output", "generic_agent_output", "workflow_recommendation"},
    "DistributionAgent": {
        "distribution_plan_output",
        "generic_agent_output",
        "workflow_recommendation",
    },
    "AuditAgent": {"audit_check_output", "generic_agent_output", "workflow_recommendation"},
    "MemoryAgent": {"memory_proposal", "generic_agent_output", "workflow_recommendation"},
    "KnowledgeAgent": {
        "knowledge_graph_proposal",
        "generic_agent_output",
        "workflow_recommendation",
    },
    "CalendarAgent": {"calendar_recommendation", "generic_agent_output", "workflow_recommendation"},
    "MetricsAgent": {"metrics_review", "generic_agent_output", "workflow_recommendation"},
}
AGENT_OUTPUT_STATUSES = {
    "created",
    "stored",
    "pending_review",
    "accepted",
    "rejected",
    "superseded",
    "blocked",
    "failed",
    "archived",
}
SENSITIVE_AGENT_OUTPUT_RISK_FLAGS = {
    "missing_source",
    "missing_verification_record",
    "missing_risk_review",
    "rumor_as_fact",
    "financial_advice_risk",
    "price_prediction_risk",
    "hallucinated_source",
    "memory_as_source_risk",
    "publication_without_approval",
    "critical_risk",
    "blocked_source_used",
}

WORKFLOW_TASK_TYPES = {
    "news_intake",
    "source_validation",
    "market_impact_assessment",
    "risk_review",
    "editorial_draft",
    "script_generation",
    "social_variant_generation",
    "distribution_planning",
    "audit_check",
    "calendar_scheduling",
    "metrics_review",
    "memory_review",
    "knowledge_update",
    "workflow_recalculation",
    "manual_review",
    "publication_preparation",
    "generic_task",
}
WORKFLOW_TASK_STATUSES = {
    "queued",
    "assigned",
    "running",
    "waiting_input",
    "waiting_review",
    "completed",
    "completed_with_warnings",
    "failed",
    "blocked",
    "cancelled",
    "retrying",
    "escalated",
    "archived",
}
WORKFLOW_TASK_PRIORITIES = {"P0", "P1", "P2", "P3", "P4"}
WORKFLOW_TASK_ASSIGNABLE_AGENTS = {
    "NewsScoutAgent",
    "SourceValidatorAgent",
    "RiskAgent",
    "MarketImpactAgent",
    "EditorialAgent",
    "ScriptAgent",
    "SocialClipAgent",
    "DistributionAgent",
    "AuditAgent",
    "MemoryAgent",
    "KnowledgeAgent",
    "CalendarAgent",
    "MetricsAgent",
    "HumanEditor",
    "Operator",
    "System",
    "None",
}

METRIC_CATEGORIES = {
    "intake_metrics",
    "source_metrics",
    "verification_metrics",
    "production_metrics",
    "publication_metrics",
    "distribution_metrics",
    "audience_metrics",
    "editorial_quality_metrics",
    "calendar_metrics",
    "agent_metrics",
    "memory_metrics",
    "incident_metrics",
    "workflow_metrics",
}
METRIC_MEASUREMENT_WINDOWS = {"1h", "24h", "7d", "30d", "90d", "custom"}
METRIC_DATA_QUALITIES = {"high", "medium", "low", "insufficient", "unknown"}

MEMORY_TYPES = {
    "source_memory",
    "editorial_memory",
    "verification_memory",
    "distribution_memory",
    "incident_memory",
    "audience_memory",
    "calendar_memory",
    "agent_memory",
    "workflow_memory",
    "risk_memory",
    "style_memory",
    "market_context_memory",
    "knowledge_memory",
}
MEMORY_STATUSES = {
    "proposed",
    "approved",
    "rejected",
    "needs_review",
    "needs_source",
    "needs_context",
    "duplicate",
    "expired",
    "invalidated",
    "archived",
}
MEMORY_CONFIDENCE_LEVELS = {"MC0", "MC1", "MC2", "MC3", "MC4", "MC5"}
MEMORY_PERSISTENCE_LEVELS = {"M0", "M1", "M2", "M3", "M4", "M5"}
MEMORY_SCOPES = {
    "item_specific",
    "source_specific",
    "topic_specific",
    "channel_specific",
    "agent_specific",
    "workflow_specific",
    "project_wide",
}
MEMORY_EXPIRATION_RECOMMENDATIONS = {
    "expires_in_24h",
    "expires_in_7d",
    "expires_in_30d",
    "expires_in_90d",
    "review_quarterly",
    "no_expiration_recommended",
}
AUTO_REVIEW_MEMORY_TYPES = {"source_memory", "risk_memory", "incident_memory"}

KNOWLEDGE_NODE_TYPES = {
    "NewsItem",
    "CandidateNewsItem",
    "SourceReference",
    "SourceReview",
    "VerificationRecord",
    "RiskReview",
    "MarketImpactAssessment",
    "EditorialOutput",
    "ContentPiece",
    "ScriptOutput",
    "SocialOutput",
    "ChannelVariant",
    "DistributionPlan",
    "PublicationRecord",
    "DistributionRecord",
    "MetricSnapshot",
    "IncidentRecord",
    "CorrectionRecord",
    "RetractionRecord",
    "AgentExecution",
    "AgentOutput",
    "MemoryItem",
    "AuditCheck",
    "CalendarItem",
    "DailyNewsroomRun",
    "EditorialDecision",
    "ORIONDocument",
    "Asset",
    "Protocol",
    "Exchange",
    "Regulator",
    "Institution",
    "Narrative",
    "Topic",
    "Channel",
    "Workflow",
    "WorkflowTask",
    "PolicyRule",
}
KNOWLEDGE_RELATIONSHIP_TYPES = {
    "derived_from",
    "uses_source",
    "validated_by",
    "risk_reviewed_by",
    "impact_assessed_by",
    "produced",
    "produced_by",
    "adapted_from",
    "distributed_by",
    "published_as",
    "measured_by",
    "caused_by",
    "corrected_by",
    "retracted_by",
    "related_to",
    "mentions",
    "affects",
    "belongs_to_category",
    "relates_to_asset",
    "relates_to_protocol",
    "relates_to_exchange",
    "relates_to_regulator",
    "relates_to_institution",
    "relates_to_narrative",
    "scheduled_in",
    "governed_by",
    "requires",
    "blocks",
    "recommends",
    "contradicts",
    "duplicates",
    "updates",
    "invalidates",
    "reinforces",
    "derived_memory_from",
    "executed_by_agent",
    "reviewed_by",
    "approved_by",
    "rejected_by",
}
KNOWLEDGE_CONFIDENCE_LEVELS = {"KC0", "KC1", "KC2", "KC3", "KC4", "KC5"}
KNOWLEDGE_SCOPES = {
    "traceability",
    "editorial_context",
    "source_context",
    "risk_context",
    "market_context",
    "distribution_context",
    "incident_context",
    "memory_context",
    "agent_context",
    "workflow_context",
    "governance_context",
}
KNOWLEDGE_STATUSES = {
    "proposed",
    "needs_review",
    "needs_source",
    "needs_verification",
    "needs_audit",
    "needs_human_review",
    "duplicate",
    "contradictory",
    "low_confidence",
    "blocked",
    "rejected",
    "approved",
    "archived",
}
